dist: xenial
language: python
python:
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"

install:
  # Initial preparation
  - pip3 install --upgrade pip
  - pip3 install coverage
  - pip3 install codecov
  - pip3 install .
script:
  - coverage run -m unittest discover tests/
after_success:
  - codecov