name: Run Flake8 Linter check for Config ORM

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master

jobs:
  linter-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies ${{ matrix.python-version }}
        run: |
          pip3 install --upgrade pip
          pip3 install .
          pip3 install flake8
          pip3 install flake8-bugbear
          pip3 install flake8-docstrings>=1.3.1
          pip3 install flake8-typing-imports>=1.1
          pip3 install pep8-naming
          pip3 install flake8-formatter-junit-xml

      - name: Run Linter
        continue-on-error: true
        run: |
          bash -ec 'mkdir -p artifacts/linter'
          flake8 --format junit-xml . > artifacts/linter/flake_junit.xml

      - name: Publish Linter artifacts
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'artifacts/linter/*.xml'
          check_name: Linter Results
          fail_on_failure: true
